# Generated by Django 4.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("source", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("last_updated", models.DateTimeField()),
            ],
            options={
                "ordering": ["-last_updated", "title"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("relevant", "Relevant"), ("irrelevant", "Irrelevant")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("content_snapshot", models.DateTimeField()),
                (
                    "content_item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="monitor.contentitem"),
                ),
                (
                    "keyword",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="monitor.keyword"),
                ),
            ],
            options={
                "ordering": ["-score", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("keyword", "content_item"), name="unique_flag_per_keyword_content")
                ],
            },
        ),
    ]
